const express = require("express");
const asyncHandler = require("../middleware/errorhandling/asynchandler");
const anyRoleAuth = require("../middleware/auth/Anyrole.middleware");
const uploadTemplate = require("../middleware/upload/TrainingTemplate.middleware");
const uploadEvidence = require("../middleware/upload/TrainingEvidence.middleware");
const training = require("../controllers/training.controller");
const router = express.Router();
router.use(anyRoleAuth);
router.get("/", asyncHandler(training.list));
router.get("/employees", asyncHandler(training.listEmployees));
router.get("/template", asyncHandler(training.getTemplate));
router.get("/report", asyncHandler(training.report));
router.post("/", asyncHandler(training.create));
router.patch("/:id/details", asyncHandler(training.updateDetails));
router.post("/template", uploadTemplate, asyncHandler(training.uploadTemplate));
router.patch("/:id/schedule", asyncHandler(training.schedule));
router.post("/:id/stages/:stage/evidence", uploadEvidence, asyncHandler(training.submitStageEvidence));
router.patch("/:id/stages/:stage/review", asyncHandler(training.reviewStage));
router.patch("/:id/submit-completion", asyncHandler(training.submitCompletion));
router.patch("/:id/decision", asyncHandler(training.decide));
router.get("/:id/certificate", asyncHandler(training.downloadCertificate));
module.exports = router;
