const mongoose = require("mongoose");


const fnfSchema = new mongoose.Schema(
  {
    organisation_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "SuperAdmin",
      required: true,
      index: true,
    },

    employee: {
      type: mongoose.Schema.Types.ObjectId,
      refPath: "employeeModel",
      required: true,
    },
    employeeModel: {
      type: String,
      required: true,
      enum: ["User", "Manager", "Admin", "SuperAdmin"],
    },

    exitType: { type: String, enum: ["resigned", "fired", "terminated"], required: true },

    dateOfJoining: { type: Date, default: null },
    dateOfResignation: { type: Date, default: null }, // date the exit was initiated / notice given
    dateOfLeaving: { type: Date, default: null }, // last working day
    settlementMonth: { type: Number, default: null, min: 1, max: 12 },
    settlementYear: { type: Number, default: null },
    totalDaysInMonth: { type: Number, default: 0 },
    payableDaysInMonth: { type: Number, default: 0 },

    employeeSnapshot: {
      name: { type: String, default: "" },
      employeeId: { type: String, default: "" }, // uid/empid
      department: { type: String, default: "" },
      designation: { type: String, default: "" },
      pan: { type: String, default: "" },
      bankAccountNumber: { type: String, default: "" },
      bankName: { type: String, default: "" },
    },

    organisationSnapshot: {
      name: { type: String, default: "" },
    },

    ctc: { type: Number, default: 0 },

    income: {
      basic: { type: Number, default: 0 },
      hra: { type: Number, default: 0 },
      allowances: [{ name: String, amount: Number, _id: false }],
      total: { type: Number, default: 0 },
    },

    otherIncome: {
      items: [{ particular: String, amount: Number, _id: false }], // e.g. leave encashment
      total: { type: Number, default: 0 },
    },

    holding: {
      salaryOnHold: { type: Number, default: 0 },
      reimbursementOnHold: { type: Number, default: 0 },
      assetRecovery: { type: Number, default: 0 },
      total: { type: Number, default: 0 },
    },

    deductions: {
      pf: { type: Number, default: 0 },
      professionalTax: { type: Number, default: 0 },
      tds: { type: Number, default: 0 },
      other: { type: Number, default: 0 },
      total: { type: Number, default: 0 },
    },

    netPayable: { type: Number, default: 0 },

    status: {
      type: String,
      enum: ["generated", "approved", "paid", "on_hold"],
      default: "generated",
    },

    autoGenerated: { type: Boolean, default: false }, // true = created by the notice-period auto-exit cron

    remarks: { type: String, trim: true, maxlength: 500, default: "" },

    generatedBy: { type: mongoose.Schema.Types.ObjectId, default: null },
    generatedByModel: { type: String, enum: ["Admin", "SuperAdmin", null], default: null },
    approvedBy: { type: mongoose.Schema.Types.ObjectId, default: null },
    approvedByModel: { type: String, enum: ["Admin", "SuperAdmin", null], default: null },
    paidOn: { type: Date, default: null },
  },
  { timestamps: true }
);


fnfSchema.index({ employee: 1 }, { unique: true });
fnfSchema.index({ organisation_id: 1, status: 1 });

module.exports = mongoose.models.FnF || mongoose.model("FnF", fnfSchema);